In [3]:
from itertools import combinations

features = ['Age', 'Income', 'Education', 'Gender', 'Location', 
            'Job', 'Credit_Score', 'Debt', 'Savings', 'Expenses']

# Generate all combinations of 3 features
feature_combos = list(combinations(features, 3))

print(f"Total combinations: {len(feature_combos)}")
print("\nFirst 50 combinations:")
for i, combo in enumerate(feature_combos[:50], 1):
    print(f"{i}. {combo}")



Total combinations: 120

First 50 combinations:
1. ('Age', 'Income', 'Education')
2. ('Age', 'Income', 'Gender')
3. ('Age', 'Income', 'Location')
4. ('Age', 'Income', 'Job')
5. ('Age', 'Income', 'Credit_Score')
6. ('Age', 'Income', 'Debt')
7. ('Age', 'Income', 'Savings')
8. ('Age', 'Income', 'Expenses')
9. ('Age', 'Education', 'Gender')
10. ('Age', 'Education', 'Location')
11. ('Age', 'Education', 'Job')
12. ('Age', 'Education', 'Credit_Score')
13. ('Age', 'Education', 'Debt')
14. ('Age', 'Education', 'Savings')
15. ('Age', 'Education', 'Expenses')
16. ('Age', 'Gender', 'Location')
17. ('Age', 'Gender', 'Job')
18. ('Age', 'Gender', 'Credit_Score')
19. ('Age', 'Gender', 'Debt')
20. ('Age', 'Gender', 'Savings')
21. ('Age', 'Gender', 'Expenses')
22. ('Age', 'Location', 'Job')
23. ('Age', 'Location', 'Credit_Score')
24. ('Age', 'Location', 'Debt')
25. ('Age', 'Location', 'Savings')
26. ('Age', 'Location', 'Expenses')
27. ('Age', 'Job', 'Credit_Score')
28. ('Age', 'Job', 'Debt')
29. ('Age',

In [4]:
from itertools import product
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

# Hyperparameter options
param_grid = {
    'n_estimators': [10, 50, 100],
    'max_depth': [5, 10, 15, 20],
    'min_samples_split': [2, 5, 10]
}

# Calculate total combinations manually
total = 1
for param, values in param_grid.items():
    total *= len(values)
    
print(f"Total hyperparameter combinations: {total}")

# Generate all combinations
all_combos = list(product(
    param_grid['n_estimators'],
    param_grid['max_depth'],
    param_grid['min_samples_split']
))

print(f"\nFirst 5 combinations:")
for i, combo in enumerate(all_combos[:5], 1):
    print(f"{i}. n_estimators={combo[0]}, max_depth={combo[1]}, min_samples_split={combo[2]}")

Total hyperparameter combinations: 36

First 5 combinations:
1. n_estimators=10, max_depth=5, min_samples_split=2
2. n_estimators=10, max_depth=5, min_samples_split=5
3. n_estimators=10, max_depth=5, min_samples_split=10
4. n_estimators=10, max_depth=10, min_samples_split=2
5. n_estimators=10, max_depth=10, min_samples_split=5


In [5]:
from itertools import combinations

models = ['Logistic Regression', 'Decision Tree', 'Random Forest', 'SVM', 'Neural Network']

ensembles = list(combinations(models, 3))

print(f"Total possible ensembles: {len(ensembles)}\n")

for i, ensemble in enumerate(ensembles, 1):
    print(f"Ensemble {i}: {', '.join(ensemble)}")

Total possible ensembles: 10

Ensemble 1: Logistic Regression, Decision Tree, Random Forest
Ensemble 2: Logistic Regression, Decision Tree, SVM
Ensemble 3: Logistic Regression, Decision Tree, Neural Network
Ensemble 4: Logistic Regression, Random Forest, SVM
Ensemble 5: Logistic Regression, Random Forest, Neural Network
Ensemble 6: Logistic Regression, SVM, Neural Network
Ensemble 7: Decision Tree, Random Forest, SVM
Ensemble 8: Decision Tree, Random Forest, Neural Network
Ensemble 9: Decision Tree, SVM, Neural Network
Ensemble 10: Random Forest, SVM, Neural Network


Problem 1: Data Augmentation - Image FlipsProblem:
You have 1 image and want to create variations using:

Original
Horizontal flip
Vertical flip
Rotate 90°
Rotate 180°
Rotate 270°
How many unique images can you create if you apply exactly 2 transformations? 


In [ ]:

from itertools import permutations

transformations = [
    'Original',
    'Horizontal flip',
    'Vertical flip',
    'Rotate 90°',
    'Rotate 180°',
    'Rotate 270°'
]

# Generate all permutations of 2 transformations
#P(6,2) = 6!/(6-2)! = 6!/4! = 6 × 5 = 30 combinations
transformation_combos = list(permutations(transformations, 2))

print(f"Total unique image variations with 2 transformations: {len(transformation_combos)}\n")

for i, combo in enumerate(transformation_combos, 1):
    print(f"{i}. {combo}")
    
    

Total unique image variations with 2 transformations: 30

1. ('Original', 'Horizontal flip')
2. ('Original', 'Vertical flip')
3. ('Original', 'Rotate 90°')
4. ('Original', 'Rotate 180°')
5. ('Original', 'Rotate 270°')
6. ('Horizontal flip', 'Original')
7. ('Horizontal flip', 'Vertical flip')
8. ('Horizontal flip', 'Rotate 90°')
9. ('Horizontal flip', 'Rotate 180°')
10. ('Horizontal flip', 'Rotate 270°')
11. ('Vertical flip', 'Original')
12. ('Vertical flip', 'Horizontal flip')
13. ('Vertical flip', 'Rotate 90°')
14. ('Vertical flip', 'Rotate 180°')
15. ('Vertical flip', 'Rotate 270°')
16. ('Rotate 90°', 'Original')
17. ('Rotate 90°', 'Horizontal flip')
18. ('Rotate 90°', 'Vertical flip')
19. ('Rotate 90°', 'Rotate 180°')
20. ('Rotate 90°', 'Rotate 270°')
21. ('Rotate 180°', 'Original')
22. ('Rotate 180°', 'Horizontal flip')
23. ('Rotate 180°', 'Vertical flip')
24. ('Rotate 180°', 'Rotate 90°')
25. ('Rotate 180°', 'Rotate 270°')
26. ('Rotate 270°', 'Original')
27. ('Rotate 270°', 'Horiz

Problem 3: Feature Interaction Terms
Problem:
You have 8 features: [X1, X2, X3, X4, X5, X6, X7, X8]
You want to create all pairwise interaction features (X1×X2, X1×X3, etc.). How many new features will you create?
Solution:
We're choosing 2 features from 8 where order doesn't matter (X1×X2 = X2×X1).
C(8,2) = 8!/(2! × 6!) = (8 × 7)/2 = 28 interaction features

In [13]:
from itertools import combinations

features = ['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8'] 

#generate all pairwise interactions (combination of 2)

interaction  =  list(combinations(features, 2))

print(f'total  pairwise interactions: {len(interaction)}\n')

for i, inter in enumerate(interaction,1):
    print(f"{i}.  {inter}")
    
#practical application: feature engineering in ML

import  numpy as np

X = np.random.rand(100,8)  #100 samples, 8 features

# Create new features based on pairwise interactions
X_interactions = np.zeros((X.shape[0], len(interaction)))

for i,(idx1, idx2) in enumerate(interaction):
    X_interactions[:,i] = X[:,features.index(idx1)] * X[:,features.index(idx2)]
    
print(f"Original feature shape: {X.shape}")
print(f"New feature shape with interactions: {X_interactions.shape}")
print(f'Combined shape : {(X.shape[0], X.shape[1] + X_interactions.shape[1])}')


total  pairwise interactions: 28

1.  ('X1', 'X2')
2.  ('X1', 'X3')
3.  ('X1', 'X4')
4.  ('X1', 'X5')
5.  ('X1', 'X6')
6.  ('X1', 'X7')
7.  ('X1', 'X8')
8.  ('X2', 'X3')
9.  ('X2', 'X4')
10.  ('X2', 'X5')
11.  ('X2', 'X6')
12.  ('X2', 'X7')
13.  ('X2', 'X8')
14.  ('X3', 'X4')
15.  ('X3', 'X5')
16.  ('X3', 'X6')
17.  ('X3', 'X7')
18.  ('X3', 'X8')
19.  ('X4', 'X5')
20.  ('X4', 'X6')
21.  ('X4', 'X7')
22.  ('X4', 'X8')
23.  ('X5', 'X6')
24.  ('X5', 'X7')
25.  ('X5', 'X8')
26.  ('X6', 'X7')
27.  ('X6', 'X8')
28.  ('X7', 'X8')
Original feature shape: (100, 8)
New feature shape with interactions: (100, 28)
Combined shape : (100, 36)


Problem 4: Voting Ensemble - Majority Vote
Problem:
You have 7 binary classifiers. You want to use majority voting (at least 4 must agree).
In how many ways can exactly 4 classifiers agree on class 1?
Solution:
We need to choose which 4 out of 7 vote for class 1:
C(7,4) = 7!/(4! × 3!) = (7 × 6 × 5)/(3 × 2 × 1) = 35 ways
All majority scenarios:

Exactly 4 agree: C(7,4) = 35
Exactly 5 agree: C(7,5) = 21
Exactly 6 agree: C(7,6) = 7
All 7 agree: C(7,7) = 1

Total: 35 + 21 + 7 + 1 = 64 ways

In [14]:
from itertools import combinations
import math

def C(n, r):
    return math.factorial(n) // (math.factorial(r) * math.factorial(n - r))

n_classifiers = 7

print("Majority voting scenarios:\n")

for k in range(4, 8):
    ways = C(n_classifiers, k)
    print(f"{k} out of {n_classifiers} vote for class 1: {ways} ways")

total = sum(C(n_classifiers, k) for k in range(4, 8))
print(f"\nTotal majority scenarios: {total}")

# Simulate ensemble voting
import numpy as np

np.random.seed(42)
predictions = np.random.randint(0, 2, (7, 100))  # 7 classifiers, 100 samples

# Majority vote
ensemble_pred = (predictions.sum(axis=0) >= 4).astype(int)

print(f"\nExample predictions (first 10 samples):")
print(predictions[:, :10])
print(f"Ensemble vote: {ensemble_pred[:10]}")

Majority voting scenarios:

4 out of 7 vote for class 1: 35 ways
5 out of 7 vote for class 1: 21 ways
6 out of 7 vote for class 1: 7 ways
7 out of 7 vote for class 1: 1 ways

Total majority scenarios: 64

Example predictions (first 10 samples):
[[0 1 0 0 0 1 0 0 0 1]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 0 0 1 0 1 1 1 0]
 [0 0 0 1 1 0 1 1 1 1]
 [1 1 0 0 1 1 1 1 1 1]
 [0 0 0 1 0 0 1 0 1 1]
 [0 1 1 1 0 0 0 1 1 1]]
Ensemble vote: [0 1 0 1 1 0 1 1 1 1]


Problem 5: Neural Network Architecture Search
Problem:
You're designing a neural network with 3 hidden layers. For each layer, you can choose:

Number of neurons: [32, 64, 128, 256]
Activation: [ReLU, Tanh, Sigmoid]

How many different architectures can you create?
Solution:
Using the multiplication principle:
For each of 3 layers:

4 choices for neurons
3 choices for activation
= 4 × 3 = 12 choices per layer

Total = 12 × 12 × 12 = 1,728 architectures

In [15]:
from itertools import product

neurons = [32, 64, 128, 256]
activations = ['ReLU', 'Tanh', 'Sigmoid']

# All combinations for one layer
layer_configs = list(product(neurons, activations))

# All combinations for 3 layers
architectures = list(product(layer_configs, repeat=3))

print(f"Configurations per layer: {len(layer_configs)}")
print(f"Total architectures (3 layers): {len(architectures)}\n")

print("First 5 architectures:")
for i, arch in enumerate(architectures[:5], 1):
    print(f"{i}. Layer1: {arch[0][0]} neurons, {arch[0][1]} | "
          f"Layer2: {arch[1][0]} neurons, {arch[1][1]} | "
          f"Layer3: {arch[2][0]} neurons, {arch[2][1]}")

print(f"\n... and {len(architectures) - 5} more architectures to explore!")

Configurations per layer: 12
Total architectures (3 layers): 1728

First 5 architectures:
1. Layer1: 32 neurons, ReLU | Layer2: 32 neurons, ReLU | Layer3: 32 neurons, ReLU
2. Layer1: 32 neurons, ReLU | Layer2: 32 neurons, ReLU | Layer3: 32 neurons, Tanh
3. Layer1: 32 neurons, ReLU | Layer2: 32 neurons, ReLU | Layer3: 32 neurons, Sigmoid
4. Layer1: 32 neurons, ReLU | Layer2: 32 neurons, ReLU | Layer3: 64 neurons, ReLU
5. Layer1: 32 neurons, ReLU | Layer2: 32 neurons, ReLU | Layer3: 64 neurons, Tanh

... and 1723 more architectures to explore!
